# Autogenerated wrapper script for Thermopack_jll for aarch64-apple-darwin-libgfortran5
export libthermopack

using CompilerSupportLibraries_jll
using OpenBLAS32_jll
JLLWrappers.@generate_wrapper_header("Thermopack")
JLLWrappers.@declare_library_product(libthermopack, "@rpath/libthermopack.dylib")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll, OpenBLAS32_jll)
    JLLWrappers.@init_library_product(
        libthermopack,
        "lib/libthermopack.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
