# Autogenerated wrapper script for Thermopack_jll for i686-w64-mingw32-libgfortran5
export libthermopack

using CompilerSupportLibraries_jll
using OpenBLAS32_jll
JLLWrappers.@generate_wrapper_header("Thermopack")
JLLWrappers.@declare_library_product(libthermopack, "libthermopack.dll")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll, OpenBLAS32_jll)
    JLLWrappers.@init_library_product(
        libthermopack,
        "bin\\libthermopack.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
